# (c) 2015 Stephen L Arnold

# add metrics test vars
CAT     = cat
MCSTRIP = ./mcstrip
CYCLO   = ./cyclo
DIFF	= diff -u

CYFLAGS = -DANSI -I./

# Compilation configuration
CC = gcc
CXX = g++
CPP = gcc -E
RM = rm -f

# we need flex to work around some limitations of certain lex versions
LEX = flex

DBG ?= -g

MYLDFLAGS	= $(CFLAGS) $(LDFLAGS) $(DBG)
MYCFLAGS	= -O2 -pipe $(CFLAGS) $(DBG)
MYCXXFLAGS	= $(MYCFLAGS)
LDADD		= -lstdc++ -lfl

.SUFFIXES:
.SUFFIXES: .o .c .C .l

GENSRCS	= mcstrip.c scan.c
BLDSRCS	= lib.C main.C
MCSOBJS	= mcstrip.o
CYCOBJS	= main.o lib.o
SCNOBJS	= scan.o

TSTSRCS = test-input.c
TSTOUT  = *.preproc *.stripped *.metrics

.INTERMEDIATE: $(GENSRCS)
.PHONY: all test
.DEFAULT: all

PGMS	= mcstrip cyclo

all: $(PGMS)

mcstrip: $(MCSOBJS)

cyclo: $(CYCOBJS) $(SCNOBJS)
	$(CXX) -o $@ $(MYCXXFLAGS) $(MYLDFLAGS) $^ $(LDADD)

test: all
	@echo "Creating test data..."
	$(CPP) $(CYFLAGS) test-input.c > test-input.c.preproc
	$(MCSTRIP) test-input.c.preproc > test-input.c.stripped
	$(CAT) test-input.c.stripped | $(CYCLO) -c > test-input.c.metrics
	@echo "Comparing test results..."
	$(DIFF) test-base.txt test-input.c.metrics

clean:
	$(RM) cyclo mcstrip core *.o *~ $(TSTOUT)

