# New simplified makefile - Updated 2015 by Stephen L Arnold
# Compilation configuration
CC = gcc
CXX = g++

# we need flex to work around some limitations of certain lex versions
LEX = flex

DBG ?= -g

MYLDFLAGS	= -O2 $(LDFLAGS) $(DBG)
MYCFLAGS	= -O2 -pipe $(CFLAGS) $(DBG)
MYCXXFLAGS	= $(MYCFLAGS)
LDADD		= -lstdc++ -lfl

.SUFFIXES:
.SUFFIXES: .o .c .C .l

GENSRCS	= mcstrip.c scan.c
BLDSRCS	= lib.C main.C strerror.c
MCSOBJS	= mcstrip.o strerror.o
CYCOBJS	= main.o lib.o
SCNOBJS	= scan.o

.INTERMEDIATE: $(GENSRCS)
.PHONY: all
.DEFAULT: all

PGMS	= mcstrip cyclo

all: $(PGMS)

mcstrip: $(MCSOBJS)

cyclo: $(CYCOBJS) $(SCNOBJS)
	$(CXX) -o $@ $(MYCXXFLAGS) $(MYLDFLAGS) $^ $(LDADD)

clean:
	$(RM) cyclo mcstrip core *.o *~

