name: ci

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04]

    steps:
    - uses: actions/checkout@v2
    - name: Add 64-bit mingw-w64 to the PATH
      run: |
        echo "c:/msys64/bin;c:/msys64/mingw64/bin" >> $GITHUB_PATH
      if: startsWith(matrix.os, 'win')

    - name: Install Ubuntu build deps
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install -y flex libfl-dev

    - name: build
      run: make

    - name: run test
      run: make -f Makefile.test test
